# 데이터셋 경로
path: ./eval/datasets/coco8  # 데이터셋 루트 디렉토리
train: images/train     # 학습 이미지 경로 (path 기준 상대경로)
val: images/val         # 검증 이미지 경로

# 클래스 개수
nc: 3  # number of classes

# 클래스 이름
names:
  0: face
  1: eye
  2: nose