# Generated by Django 5.2 on 2025-04-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='embedding',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='meta',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
